### ISSUE TITLE
[Bug]Only one instance of an object can be hit by bullets during each wave of enemy generation.

### ISSUE THREAD

**Issue by TKcollecting** [syun77/godot_stg_test#1]
Running on Godot 4.1.1.
For example, when the first wave of objects is generated, only the enemy object on the left side can be hit by the player's bullets.
![image](https://github.com/syun77/godot_stg_test/assets/87885266/ca3d1ae6-bc35-46a8-b2d2-601ccca58edd)
_This is the second wave.The actual effect is the same as the first wave._
Because it's spawned earlier than the object on the right side in function:
```
func update():
	while true:
		await get_tree().create_timer(1).timeout
		spawn(1, 270-45, 300) # could be hit
		spawn(1, 270+45, 300) # could not be hit
		await get_tree().create_timer(2).timeout
		await get_tree().create_timer(2).timeout
```
_This function is in Boss.gd_

I suspect there is something wrong with this function in Shot.gd:
```
func _on_Shot_area_entered(area):
	if "Enemy" in area.name or "Boss" in area.name:
		area.hit(1) # 敵に1ダメージ
		queue_free()
```

**Comment by syun77** [comment]
In Godot4.x, the instance name is now created using the type name, so it seems that the determination using "name" cannot be worked.

Therefore, I modified it to detect based on the class name.

```gdscript
func _on_Shot_area_entered(area:Area2D):
	# cannot be detected by name in godot 4.x.
	#if "Enemy" in area.name or "Boss" in area.name:
	if area is Enemy or area is Boss:
		area.hit(1) # 敵に1ダメージ
		queue_free()
```

Enemy.gd
```gdscript
class_name Enemy
```

Boss.gd
```gdscript
class_name Boss
```
